name: timemastermobile_front
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Correct asset configuration
  assets:
    - images/logos/
    - images/covers/
    - images/graphic-icons/
    - images/Login/
    - images/persons/
    
